### ISSUE TITLE
delivery page : tabs displayed even if tnt is not selected

### ISSUE THREAD

**Issue by lunika** [thelia-modules/TNTFrance#2]
If you have more than one delivery module activated, tnt can be in second position. So when the page is loaded, tnt is not selected but you can see the tabs "Home Delivery", "TNT Depot" and "Drop Off Point".

It will be great to hide/show the tabs if tnt is selected or not.

**Comment by Yochima** [comment]
Problem solved in the version 1.1.2 
Thx !
